name: BuildAndTest

on: pull_request

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Go modules
      run: go mod download

    - name: Validate go.mod is tidy
      run: |
        go mod tidy
        git diff --exit-code go.mod go.sum
      continue-on-error: true

    - name: Validate formatting
      run: test -z $(find . -name "*.go" | xargs gofmt -s -l)

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.56
      continue-on-error: true

    - name: Build
      run: go build -o . ./...

    - name: Test
      run: go test -v ./...

    - name: e2e Test, validate no diffs
      run: |
        ./test
        test -z "$(git status --porcelain)"
